### ISSUE TITLE
error (also thanks for save the entire yuzu repos :)

### ISSUE THREAD

**Issue by paypay-a** [yuzu-mirror/yuzu#1]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

latest

### Description of Issue

CMake Error at externals/oaknut/CMakeLists.txt:15 (message):
  In-source builds are not allowed.

CMake Error at /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/CMakePackageConfigHelpers.cmake:344 (configure_file):
  configure_file attempted to configure a file:
  /Users/paitonbertschy/yuzu/externals/oaknut/oaknutConfig.cmake into a
  source directory.
Call Stack (most recent call first):
  externals/oaknut/CMakeLists.txt:115 (configure_package_config_file)

from the terminal

### Expected Behavior

.

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by cartercanedy** [comment]
You need to create a build subdirectory (by convention named"build") and run cmake after cd'ing into it

**Comment by paypay-a** [comment]
it did the same thing after doing that

**Comment by ascpixi** [comment]
Thanks for reporting! Did this error occur after following the instructions over at the [wiki](https://github.com/yuzu-mirror/yuzu/wiki/Building-for-Linux)?

**Comment by toriningen** [comment]
Or `git reset --hard && git clean -fdx` instead of recloning

**Comment by paypay-a** [comment]
> Or `git reset --hard && git clean -fdx` instead of recloning

thanks this helped in the fix for me to build it! i now have a working binary for macOS if anyone would like to get a download link
