### ISSUE TITLE
Hello Linuxes!

### ISSUE THREAD

**Issue by TuxJuniorLinux** [yuzu-mirror/yuzu#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Pls linux

### Description of Issue

Helo. I don't see any Linus. Can you make a Lenux Version? Please. I am a Lenus. Thanks.
![tux](https://github.com/yuzu-mirror/yuzu/assets/162382189/17ad61a6-909f-4c2f-9f8c-d3c55651cd47)

### Expected Behavior

Pls linux

### Reproduction Steps

Linux Tech Tips

### Log File

Linux

### System Configuration

CPU:Lenux
GPU/Driver:Lenux
RAM:Lenux
OS:Lenux

**Comment by ascpixi** [comment]
![eminem](https://github.com/yuzu-mirror/yuzu/assets/44982772/f7149b59-04d1-43bb-9137-129fbe3caa6f)

**Comment by Hunterrules0-0** [comment]
just compile it for linux
