### ISSUE TITLE
/external: some directories link to commits not in linked repo

### ISSUE THREAD

**Issue by T0x1cL** [yuzu-mirror/yuzu#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

This affects building rather than a specific build.

### Description of Issue

In the `externals` directory in this repository, there are a number of links which point to a specific commit in another repo (e.g. [breakpad @ c89f9dd](https://github.com/yuzu-mirror/breakpad/tree/c89f9dddc793f19910ef06c13e4fd240da4e7a59)). This causes a `git upload-pack: not our ref` error and breaks building with a modified [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yuzu-git) when the process running the script tries to `git submodule update`.

This can possibly be fixed by setting up the submodules and then `git commit -a`, but I have not yet found a way to do this with `makepkg`. If this is fixed at the source level it should be possible to use this organisation's repos as drop-in replacements for the ones rendered inaccessible for the purpose of building a yuzu Arch Linux package.

### Expected Behavior

The package is built successfully. (`yuzu-git-$pkgver.pkg.tar.zst` is built.)

### Reproduction Steps

[PKGBUILD.txt](https://github.com/yuzu-mirror/yuzu/files/14502734/PKGBUILD.txt)
Attached is a copy of the edited `yuzu-git` PKGBUILD which I used (`yuzu-emu` and `merryhime` changed to `yuzu-mirror`).

1. have a working Arch Linux (or derivative) that is ready to use the AUR (requires the `base-devel` package)
2. download, rename to `PKGBUILD` (from `PKGBUILD.txt`), and run `makepkg -s`

### Log File

[log.txt](https://github.com/yuzu-mirror/yuzu/files/14502808/log.txt)
(manually copied from terminal into a text file)

### System Configuration

CPU: Ryzen 7 5800X
GPU/Driver: RX 6700 XT (amdgpu)
RAM: 16 GiB
OS: Artix Linux

**Comment by ascpixi** [comment]
I think it might just be easier (and more faithful to the original repos) to bring the referenced repos to the referenced commits. Both `yuzu` and `yuzu-mainline` point to `breakpad @ c89f9dddc793f19910ef06c13e4fd240da4e7a59`, for example.

**Comment by ascpixi** [comment]
Looks like `breakpad` was the only repo that was missing a commit. It was brought to [c89f9dd](https://github.com/yuzu-mirror/breakpad/tree/c89f9dddc793f19910ef06c13e4fd240da4e7a59). Can you see if the issue still persists after the update? @T0x1cL

**Comment by T0x1cL** [comment]
@ascpixi `breakpad` seems to work now, but `mbedtils` seems to also be missing a commit

```
Synchronizing submodule url for 'externals/mbedtls'
Cloning into '/home/toxl/build/yuzu-git/src/yuzu/externals/mbedtls'...
done.
fatal: git upload-pack: not our ref 8c88150ca139e06aa2aae8349df8292a88148ea1
fatal: remote error: upload-pack: not our ref 8c88150ca139e06aa2aae8349df8292a88148ea1
fatal: Fetched in submodule path 'externals/mbedtls', but it did not contain 8c88150ca139e06aa2aae8349df8292a88148ea1. Direct fetching of that commit failed.
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by ascpixi** [comment]
`mbedtls` now includes all branches and commits from the original yuzu-emu org. How about now? @T0x1cL

**Comment by T0x1cL** [comment]
Builds correctly. Thank you!
[PKGBUILD.txt](https://github.com/yuzu-mirror/yuzu/files/14503738/PKGBUILD.txt)
Here's the final PKGBUILD which I used. (I changed yuzu-mirror/oaknut back to merryhime/oaknut.)
