### ISSUE TITLE
Suggestion: Rename this Yuzu mirror to Nuzu

### ISSUE THREAD

**Issue by kleinfisch** [yuzu-mirror/yuzu#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Rename this mirror of Yuzu to Nuzu (New-zu) to signify it being something different, as it is definitely not yuzu as yuzu cannot legally exist.

### Why would this feature be useful?

-It would be funny
-Shhh its definitely not Yuzu

**Comment by BaccarWozat** [comment]
There's a lot of ideas had by a lot of people who've made a lot of forks. Maybe "Bozo" would be good.

**Comment by ascpixi** [comment]
The organization's purpose is to maintain a frozen mirror fork (or, in other words, an archive) of what once was the Yuzu emulator - renaming it would suggest it's an unofficial continuation. I'm afraid there's not going to be any new features or improvements to the emulator (there are unofficial continuations of Yuzu already out there - suyu, for example).
