### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by TeaqariaWTF** [yuzu-mirror/yuzu#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Support Android 

### Why would this feature be useful?

Will there be a version available for Android devices

**Comment by ascpixi** [comment]
You should be able to build yuzu the same way as you'd do with the original repository. If you're looking for ready Android builds, you can find them [here](https://github.com/pineappleEA/pineapple-src/releases). These were early-access though.
