### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ImportTaste** [yuzu-mirror/yuzu#6]
Is there any way to restore the tags for all the different versions? I've yet to come across a backup that's done so.

**Comment by HANDZCZ** [comment]
I don't know if it helps, but you can try https://archive.org/details/yuzu-emu_GitHub_03-04-2024.
According to [this comment](https://www.reddit.com/r/yuzu/comments/1b76efw/comment/ktggfh6/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), it should have all repos and tags.
In the comments on archive.org, you can also find a backup of issues and PRs from the main repo.

**Comment by toriningen** [comment]
@ImportTaste https://gist.github.com/toriningen/bafee02bbe5bdb51c8b8c3bccec3d1af here you have list of all tags. Only two repos had them

**Comment by ascpixi** [comment]
Tracked in #10.
